name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-to-test-env:
    runs-on: ubuntu-latest
    environment:
      name: test
    name: deploy-to-test
    steps:
      - uses: kachick/wait-other-jobs@v3.6.0
        timeout-minutes: 24
        with:
          wait-list: |
            [
              {
                "workflowFile": "lint.yml"
              },
              {
                "workflowFile": "test.yml"
              },
              {
                "workflowFile": "sdk.yml"
              },
              {
                "workflowFile": "build.yml"
              }
            ]
      - run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITAL_OCEAN_TOKEN }}" "https://api.digitalocean.com/v2/apps/${{ secrets.DIGITAL_OCEAN_APP_ID }}/deployments" -d '{ "force_build": true }' | jq -e .deployment.id
