name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-to-test-env:
    runs-on: ubuntu-latest
    environment: Test
    name: deploy-to-test
    steps:
      - uses: kachick/wait-other-jobs@v3.6.0
        timeout-minutes: 24
        env:
          TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          URL: ${{ vars.DEPLOYMENT_URL }}
        with:
          wait-list: |
            [
              {
                "workflowFile": "lint.yml"
              },
              {
                "workflowFile": "test.yml"
              },
              {
                "workflowFile": "sdk.yml"
              },
              {
                "workflowFile": "build.yml"
              }
            ]
      - run: |
          set -eo pipefail
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" --url "$URL" -d '{ "force_build": true }' | jq -e .deployment.id
